# docker-compose.yml

version: "3.8"

services:
  web:
    build: .
    container_name: fastapi-server-nearest-airport
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8008:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: postgres-nearest-airport
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env
  redis:
    image: redis:latest
    container_name: redis-nearest-airport
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  postgres_data:
  redis-data:
